
name: build openwrt r7800

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      openwrtBranch:
        description: 'input openwrt branch'
        required: true
        default: 'openwrt-21.02'
      configFile:
        description: 'input openwrt config file name'
        required: true
        default: 'config-r7800-2102'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Get openwrt source code
        run: |
          git clone https://github.com/openwrt/openwrt.git -b ${{ github.event.inputs.openwrtBranch }}
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Get argon theme
        run: |
          cd openwrt/package
          git clone https://github.com/jerrykuku/luci-theme-argon.git
      
      - name: Load custom file for r7800
        id: custom
        run: |
          cp ${{ github.event.inputs.configFile }} openwrt/.config
          chmod +x ./scripts/*.sh
          cp -p ./scripts/install_custom_conf.sh openwrt/
          cd openwrt
          ./install_custom_conf.sh
      
      - name: Download package
        id: download
        if: steps.custom.conclusion  == 'success'
        run: |
          cd openwrt
          make defconfig
          make download -j4
      
      - name: Compile Tools
        id: tools
        if: steps.download.conclusion  == 'success'
        run: |
          cd openwrt
          make tools/compile -j4
          
      - name: Compile Toolchain
        id: toolchain
        if: steps.tools.conclusion == 'success'
        run: |
          cd openwrt
          make toolchain/compile -j4
      
      - name: Compile package compile
        id: package
        if: steps.toolchain.conclusion  == 'success'
        run: |
          cd openwrt
          make diffconfig
          make package/compile V=s
      
      - name: Compile firmware
        id: firmware
        if: steps.package.conclusion  == 'success'
        run: |
          cd openwrt
          make V=s
          echo "::set-output name=status::success"
          
      - name: Upload bin directory
        uses: actions/upload-artifact@main
        if: steps.firmware.outputs.status == 'success'
        with:
          name: ${{ github.event.inputs.openwrtBranch }}
          path: openwrt/bin/targets
